CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../conll09/sentences-chinese.txt --output_file=../conll09/sentences-chinese.txt.bert.chinese.cased.hdf5 --vocab_file=../bert-models/chinese_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/chinese_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/chinese_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../conll09/sentences-czech.txt --output_file=../conll09/sentences-czech.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../conll09/sentences-german.txt --output_file=../conll09/sentences-german.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../conll09/sentences-japanese.txt --output_file=../conll09/sentences-japanese.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../conll09/sentences-spanish.txt --output_file=../conll09/sentences-spanish.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

