CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-en-sentences.txt --output_file=../ud/ud2.1-en-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/cased_L-24_H-1024_A-16/vocab.txt --bert_config_file=../bert-models/cased_L-24_H-1024_A-16/bert_config.json --init_checkpoint=../bert-models/cased_L-24_H-1024_A-16/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-bg-sentences.txt --output_file=../ud/ud2.1-bg-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-ca-sentences.txt --output_file=../ud/ud2.1-ca-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-cs-sentences.txt --output_file=../ud/ud2.1-cs-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-de-sentences.txt --output_file=../ud/ud2.1-de-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-es-sentences.txt --output_file=../ud/ud2.1-es-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-fr-sentences.txt --output_file=../ud/ud2.1-fr-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-it-sentences.txt --output_file=../ud/ud2.1-it-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-nl-sentences.txt --output_file=../ud/ud2.1-nl-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-no-sentences.txt --output_file=../ud/ud2.1-no-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-ro-sentences.txt --output_file=../ud/ud2.1-ro-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8

CUDA_VISIBLE_DEVICES=1 python extract_features_hdf5.py --input_file=../ud/ud2.1-ru-sentences.txt --output_file=../ud/ud2.1-ru-sentences.txt.bert.multi.cased.hdf5 --vocab_file=../bert-models/multi_cased_L-12_H-768_A-12/vocab.txt --bert_config_file=../bert-models/multi_cased_L-12_H-768_A-12/bert_config.json --init_checkpoint=../bert-models/multi_cased_L-12_H-768_A-12/bert_model.ckpt --layers=-2 --max_seq_length=512 --batch_size=8
